### ISSUE TITLE
USER STORY: View home page

### ISSUE THREAD

**Issue by puma13992** [puma13992/cinematography#1]
As a visitor I can view the homepage so that I can see the description of the website, the newest movies posts and in a sidebar the most popular movie posts.

### Acceptance Criteria:

- Display a start screen with information about the purpose of the website and the newest movie posts
- Display

### Tasks:

- [x]  Create and style the components for the start screen (description, how-to, newest movies)
- [x] Create functionality to show a short video first
- [x] Add URL path
