### ISSUE TITLE
USER STORY: Delete movie

### ISSUE THREAD

**Issue by puma13992** [puma13992/cinematography#10]
As an authenticated user I can delete my own movie so that I keep it up to date.

### Acceptance Criteria:

- As an authenticated user I can delete my own movie.
- As an authenticated user I can`t see the deleted items anymore.

### Tasks:

- [x] Create working form to delete items
- [x] Add the functionality so that the user can delete his/her own movie
- [x] Add the functionality so that the user can`t see his/her deleted movie anymore
