### ISSUE TITLE
USER STORY: Add comment

### ISSUE THREAD

**Issue by puma13992** [puma13992/cinematography#11]
As an authenticated user I can add a comment to other users' movies.

### Acceptance Criteria:

- As an authenticated user I can add a comment.
- As an authenticated user I can see the new added comment.

### Tasks:

- [x] Create working form to add a comment
- [x] Add the functionality so that the user can add a comment
- [x] Add the functionality so that the user can see his/her comment
