### ISSUE TITLE
USER STORY: Delete comment

### ISSUE THREAD

**Issue by puma13992** [puma13992/cinematography#13]
As an authenticated user I can delete my own comment so that I keep it up to date.

### Acceptance Criteria:

- As an authenticated user I can delete my own comment.
- As an authenticated user I can`t see the deleted comment anymore.

### Tasks:

- [x] Create working form to delete a comment
- [x] Add the functionality so that the user can delete his/her own comment
- [x] Add the functionality so that the user can`t see his/her deleted comment anymore
