### ISSUE TITLE
USER STORY: Search and filter movies

### ISSUE THREAD

**Issue by puma13992** [puma13992/cinematography#18]
As a visitor/user I want to be able to search movies and filter them by username, title, release, director and content keywords so that I can search specific movies and I want to filter them by specific categorys.

### Acceptance Criteria:

- As a visitor/user I can search movies via the search bar.
- As a visitor/user I can search movies by username, title, release, director and content keywords.
- As a visitor/user I can filter movies by specific categorys.

### Tasks:

- [x] Add the functionality so that the visitor/user can search movies via the search bar
- [x] Add the functionality so that the visitor/user can search specificly by username, title, release, director and content keywords
- [x] Add the functionality so that the visitor/user can filter movies by specific categorys.
