### ISSUE TITLE
DEVELOPER STORY: Manual & automated testing

### ISSUE THREAD

**Issue by puma13992** [puma13992/cinematography#19]
As a developer I test my project so that I can find and fix potential bugs.

### Acceptance Criteria:

- As a developer I set up automated testing.
- As a developer I`ll test the frontend manually.

### Tasks:

- [x] Setup automated testing for the backend and frontend
- [x] Use PEP8 for the backend
- [x] Use Eslint for the frontend
- [x] Test the project manually and intensively
- [x] Look for bugs 
- [x] Fix found bugs (if possible)
- [x] Note the results in the readme file
