### ISSUE TITLE
USER STORY: User registration

### ISSUE THREAD

**Issue by puma13992** [puma13992/cinematography#2]
As a visitor I can register on the site so that I can get an account.

### Acceptance Criteria:

- As a visitor I can find the register link in the nav bar.
- As a visitor I can create an account at the register page and choose my credentials.

### Tasks:

- [x] Create and style a register page 
- [x] Add menu item/correct link in the nav bar
- [x] Add URL path
- [x] Use the django-rest-auth library
- [x] Create the functionality to create an account
