### ISSUE TITLE
USER STORY: Add glossary term

### ISSUE THREAD

**Issue by puma13992** [puma13992/cinematography#21]
As an authenticated user I can add a glossary term so that other visitors/users can see it.

### Acceptance Criteria:

- As an authenticated user I can add a glossary term.
- As an (authenticated) user or visitor I can see the new added glossary term.

### Tasks:

- [x] Create working form to add a glossary term
- [x] Add the functionality so that the user can add a glossary term
- [x] Add the functionality so that every user can see the added glossary term on the glossary page
