### ISSUE TITLE
USER STORY: Edit glossary term

### ISSUE THREAD

**Issue by puma13992** [puma13992/cinematography#22]
As an authenticated user I can edit every glossary term so that I can keep it up to date.

### Acceptance Criteria:

- As an authenticated user I can find a form to edit every glossary term.
- As an authenticated user I can edit the glossary term.
- As an (authenticated) user/visitor I can see the edited glossary term with a ‘Updated by username’ and ‘Last update: Date’ label.

### Tasks:

- [x] Create working form which gives the ability to the user to edit any glossary term
- [x] Style the form
- [x] Add URL path
