### ISSUE TITLE
USER STORY: Delete glossary term

### ISSUE THREAD

**Issue by puma13992** [puma13992/cinematography#23]
As an authenticated user I can delete my own glossary term so that I keep it up to date.

### Acceptance Criteria:

- As an authenticated user I can delete my own glossary term.
- Nobody can see the deleted comment glossary term anymore after deleting.

### Tasks:

- [x] Create working form to delete a glossary term
- [x] Add the functionality so that the user can delete his/her own glossary term
- [x] Add the functionality so that nobody can`t see a deleted glossary term anymore
