### ISSUE TITLE
USER STORY: Navigate the site

### ISSUE THREAD

**Issue by puma13992** [puma13992/cinematography#3]
As a user/visitor I can navigate through the whole website so that I can explore the benefit of it.

### Acceptance Criteria:

- As a user I can find the navbar on each page.
- As a user I can view the navbar and read it's content.
- As a user I can click on the navbar items and every item worked.

### Tasks:

- [x] Create and style navbar
- [x] Create navbar items
- [x] Create working links for each navbar item
