### ISSUE TITLE
USER STORY: Login to account

### ISSUE THREAD

**Issue by puma13992** [puma13992/cinematography#4]
As a user I can log into my account after registration so that I can get extra functionality, e.g. add, edit and delete a movie.

### Acceptance Criteria:

- As a registered user I can find the login item in the navbar.
- As a registered user I can click on the login item in the navbar which goes to the login page.
- As a registered user I can log in with my login details which I have registered.
- As an authenticated user I can see my profile page if I`m logged in.

### Tasks:

- [x] Create and style the login page
- [x] Add navbar item/correct link for login in the navbar
- [x] Use the django-rest-auth library
- [x] Create the functionality for the user to login properly with his/her registered data
- [x] Add navbar item/correct link for the profile page in the navbar which is only shown to user who logged in
- [x] Add URL paths for login page
