### ISSUE TITLE
USER STORY: Edit profile

### ISSUE THREAD

**Issue by puma13992** [puma13992/cinematography#7]
As an authenticated user I can edit my profile in my account so that I can keep it up to date.

### Acceptance Criteria:

- As an authenticated user I can find a button on my profile page to edit my profile.
- As an authenticated user I can edit my profile, such as profile picture, description etc.
- As an authenticated user I can see the edited items.

### Tasks:

- [x] Create and style profile page
- [x] Add the functionality so that the user can edit his/her profile
- [x] Add URL path
