### ISSUE TITLE
USER STORY: Add movie

### ISSUE THREAD

**Issue by puma13992** [puma13992/cinematography#8]
As an authenticated user I can add a movie so that other users can see/find it.

### Acceptance Criteria:

- As an authenticated user I can add a movie.
- As an authenticated user I can see the new added movie.

### Tasks:

- [x] Create working button to add movie
- [x] Add the functionality so that the user can add a movie
- [x] Add the functionality so that the user can see his/her movie
