### ISSUE TITLE
USER STORY: Edit movie

### ISSUE THREAD

**Issue by puma13992** [puma13992/cinematography#9]
As an authenticated user I can edit my own movie so that I can keep it up to date.

### Acceptance Criteria:

- As an authenticated user I can find a form to edit my movie.
- As an authenticated user I can edit my movie.
- As an authenticated user I can see the edited items.

### Tasks:

- [x] Create working form which gives the ability to the user to edit his/her own movie
- [x] Style the form
- [x] Add URL path
